[project]
name = "python-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "extruct>=0.18.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "tls-client>=1.0.1",
    "typing-extensions>=4.12.2",
]
